#!/bin/sh

if [ -d "/var/secrets" ]
then
    tmpfile="$(mktemp)"

    for file in /var/secrets/* do
        if [ -f $file ]
        then
            file_contents=$(cat $file)
            filename=$(basename "$file")
            underscored_filename="${filename//-/_}"
            capitalized_filename=${underscored_filename^^}

            echo "export $capitalized_filename=$file_contents" >> $tmpfile
        fi

        source $tmpfile
        rm -f $tmpfile
    done
fi

exec "$@"
