#!/bin/bash
set -ex

echo "=> Building binary"
docker run --rm -v "$PWD:/usr/src/github-hook-receiver" -w "/usr/src/github-hook-receiver" golang:1.7.3 \
       go-wrapper download \
       && go-wrapper install \
       && go build -v

echo "=> Adding label-schema.org labels"
echo "LABEL org.label-schema.build-data\"$(date --rfc-3339=seconds)\" \
            org.label-schema.vcs-ref=\"${SOURCE_COMMIT}\" \
            org.label-schema.version=\"${DOCKER_TAG}\"" >> Dockerfile
