#!/bin/sh

while true; do
    read -p "[yn] Do you wish to set the GITHUB_SECRET for the github-hook-receiver service? If you have already done so and it did not change just choose No." yn
    case $yn in
        [Yy]* )
            read -p "GITHUB_SECRET: " gh_secret
            echo $gh_secret | docker run --rm -i -v github-hook-receiver-secrets:/var/cache/secrets alpine:3.4 dd of=/var/cache/secrets/GITHUB_SECRET
            break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done